{"uuid":"45e1d574-914b-4aed-b6c1-a9566b8cd468","historyId":"79f19fdd12924a8cadbe92f236e73876","fullName":"tests.authen.LoginTestWithDataBuilder.testLogin","labels":[{"name":"package","value":"tests.authen.LoginTestWithDataBuilder"},{"name":"testClass","value":"tests.authen.LoginTestWithDataBuilder"},{"name":"testMethod","value":"testLogin"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"appium-mobile"},{"name":"subSuite","value":"tests.authen.LoginTestWithDataBuilder"},{"name":"host","value":"DESKTOP-0F0OE94"},{"name":"thread","value":"19908@DESKTOP-0F0OE94.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testLogin","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.RuntimeException: \\src\\test\\java\\test_data\\authen\\LoginCreds.json","trace":"java.lang.RuntimeException: java.lang.RuntimeException: \\src\\test\\java\\test_data\\authen\\LoginCreds.json\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:153)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:767)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:704)\r\n\tat org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:70)\r\n\tat org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:49)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:904)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:808)\r\n\tat org.testng.TestRunner.run(TestRunner.java:603)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:429)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:326)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1169)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1092)\r\n\tat org.testng.TestNG.run(TestNG.java:1060)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\nCaused by: java.lang.RuntimeException: \\src\\test\\java\\test_data\\authen\\LoginCreds.json\r\n\tat test_data.DataObjectBuilder.buildDataObject(DataObjectBuilder.java:26)\r\n\tat tests.authen.LoginTestWithDataBuilder.LoginCredentialData(LoginTestWithDataBuilder.java:32)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)\r\n\t... 24 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1659531406244,"stop":1659531406246}